### ISSUE TITLE
[OAuth2] Gender, Address and Birthday are not mapped properly from SSO

### ISSUE THREAD

**Issue by Guichaguri** [sleede/fab-manager#365]
I'm configuring a new Fab-Manager installation with OAuth 2.0 authentication, I've mapped most user and profile properties, and all of them work as expected, except the gender, address and birthday.

The gender, birthday and address fields are disabled and empty, and as the gender field is required, a new user can't complete their profile, being stuck in the profile completion page no matter what.
![image](https://user-images.githubusercontent.com/1813032/173156218-ff2673a3-4338-4d88-95a9-7dbfa0352912.png)

The mapping for these fields is correct and configured properly. I've tried setting the gender to both a boolean property and creating a string to boolean mapping, but none of them worked.

Is there anything I'm doing wrong or is it an issue with Fab-Manager itself?

Also, not fully related to this issue, the group can be changed by the user in the profile completion page, even if that property comes from OAuth 2.

Thanks!

**Comment by sylvainbx** [comment]
Seems like a bug to me. Thanks for reporting. I'll try to reproduce it and keep you updated.

**Comment by sylvainbx** [comment]
I've not reproduced the issue directly but fixed some things related to thoses issues (and I fixed group changing on profile completion page). Can you try upgrading to v5.4.5 or above and keep me updated?

**Comment by Guichaguri** [comment]
I'm currently running 5.4.10 and still facing the same issue.

Here's the JSON returned by the user endpoint URL:
```json
{
	"uid": "username",
	"username": "username",
	"email": "example@example.com",
	"is_allow_contact": true,
	"is_allow_newsletter": false,
	"gender": "M",
	"isMale": true,
	"birthday": "1996-02-26T00:00:00.000Z",
	"phone": "",
	"first_name": "GUILHERME",
	"last_name": "CHAGURI"
}
```

The properties are mapped 1:1 from the user endpoint URL and FabManager properties
The birthday one is also mapped to receive ISO 8601 dates.
I've tried both the `gender` property (mapping M to true and F to false) and the `isMale` property (with no mapping), but none of them worked.
The gender field and the birthday are still disabled in 5.4.10, even though they are not filled.
![image](https://user-images.githubusercontent.com/1813032/177551683-0da110e2-fc69-4e96-b889-55e2ed268fd7.png)

Upon further inspection of the member request, both fields are present in `mapped_from_sso`, the gender is an empty string and the birthday is null:
![image](https://user-images.githubusercontent.com/1813032/177551110-af65a78f-0f59-4e91-87de-370726906268.png)

Thanks for the help!

**Comment by sylvainbx** [comment]
This should be fixed in [v5.4.11](https://github.com/sleede/fab-manager/releases/tag/v5.4.11). Please feel free to reopen if this is still happening.

**Comment by sylvainbx** [comment]
Well actually, I found another related issue, [v5.4.12](https://github.com/sleede/fab-manager/releases/tag/v5.4.12) might definitely fixes the issue :sweat_smile:

**Comment by Guichaguri** [comment]
That definitely fixed it! Thank you 😄
